FROM golang:1.25-alpine

ARG AIR_VERSION=v1.63.4
RUN apk add --no-cache git ca-certificates && \
    go install github.com/air-verse/air@${AIR_VERSION}

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
CMD ["air", "-c", ".air.toml"]
