root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/api ./cmd/api"
bin = "./tmp/api"
include_ext = ["go", "sql", "toml"]
exclude_dir = ["tmp", "vendor"]
delay = 300
stop_on_error = true

[misc]
clean_on_exit = true
